### ISSUE TITLE
Warehouse - Parent for sublocation

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#1]
Section wajib mempunyai parent warehouse, location wajib mempunyai parent section. Saat ini masih bisa disave walaupun tidak ditentukan parentnya.

**Comment by komsel2228** [comment]
saya ada customize form warehouse. tapi ini saya usahakan tidak merubah code dasarnya.
1. Jika type dipilih "Section" maka Parent "Warehouse" akan muncul dan dapat dipilih
![section1](https://user-images.githubusercontent.com/8717967/36467290-b21b51ac-1710-11e8-8119-c9716325a960.png)

2. Jika type dipilih "Location" maka Parent "Section" dan "Warehouse" akan muncul dan dapat dipilih
![location1](https://user-images.githubusercontent.com/8717967/36467315-c62d5758-1710-11e8-82e4-8d3fab052753.png)

**Comment by hokgt** [comment]
Yang perlu direvisi: 
1. Tab Tree Details setiap pembuatan record baru selalu dalam keadaan terbuka
2. Parent Section RSS diubah menjadi Parent Section
3. Warehouse name diubah menjadi Name

**Comment by komsel2228** [comment]
1. itu standar dari ERPNextnya. kalo dibuat dari sana, ada bugsnya. harus Pull Request ini.
2. Ini saya lupa ubah, sudah saya rubah.
3. untuk nama warehouse name jadi name. sudah saya sesuaikan.
![screen3](https://user-images.githubusercontent.com/8717967/36522602-1eb0689c-17d0-11e8-840a-948ad8dd8875.png)
