### ISSUE TITLE
Packing - Remove expedition

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#10]
Pada proses packing, pic tidak mengetahui expedisi apa yang dipakai melainkan ditentukan oleh bagian logistik, sehingga field input untuk expedition dihapus dari packing dan hanya ditampilkan di form delivery order dan delivery keeptrack yang merupakan tanggung jawab dari logistik

**Comment by komsel2228** [comment]
sudah di hilangkan expedition-nya dari Packing Order
![packing](https://user-images.githubusercontent.com/8717967/36475866-b367a70e-172e-11e8-8b32-6c07b54e2587.png)
