### ISSUE TITLE
Receive Order - Received Item List View

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#103]
Pada PO-01 terdapat 3 item, user generate RO-01 untuk salah satu item diterima dengan quantity full sesuai dengan PO. Ketika user generate lagi RO-02 dengan get item from PO, item yang diterima full juga tetap muncul di List View yang seharusnya jika sudah full receive tidak boleh  muncul lagi.
![whatsapp image 2018-06-05 at 18 16 11](https://user-images.githubusercontent.com/15005756/40973431-6b34d300-68ee-11e8-8914-fb15a62f9923.jpeg)

**Comment by goldentrepo** [comment]
done

**Comment by hokgt** [comment]
Tidak dapat di test karena get item error.

**Comment by goldentrepo** [comment]
dicoba lagi koh buat dokumen baru
