### ISSUE TITLE
Item - Stock Mistake

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#104]
Pada item A-04BL current stock adalah 174 pcs, antrian SO adalah 183 pcs yang dimana sudah melebihi available stock, akan tetapi ketika diinput dalam SO item tersebut tidak ada peringatan pada saat SO disubmit. 

Akan tetapi tidak terjadi hal yang sama pada item yang lain. 

<img width="1266" alt="screen shot 2018-06-06 at 14 27 34" src="https://user-images.githubusercontent.com/15005756/41023392-7e05e0e8-6996-11e8-9ace-16bb330392f6.png">

**Comment by goldentrepo** [comment]
ini kemungkinan ada SO yang ga masukin gudangnya koh, jadi dia ga masuk ke perhitungan yang sudah dibuat hendrik.

**Comment by hokgt** [comment]
Kalau begitu warehouse routing harus mandatory.

**Comment by goldentrepo** [comment]
done
