### ISSUE TITLE
Workflow - Packing to Delivery 

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#109]
Pada saat ini workflow setelah Packing adalah : 
Packing - SI - DO - DK - DR (jika ada)

Workflow ini diubah menjadi : 
Packing - DO - SI - DK - DR

Impact yang terjadi atas perubahan ini adalah:
1. DO yang akan mengupdate status menjadi waiting for delivery
2. SI hanya bisa dibuat jika SO yang sudah ada DO nya
3. DK hanya bisa dibuat jika SO yang sudah ada SI nya

**Comment by goldentrepo** [comment]
done
