### ISSUE TITLE
Packing - Barcode auto generated

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#11]
Auto generate barcode di packing tidak tampil

**Comment by komsel2228** [comment]
![packing1](https://user-images.githubusercontent.com/8717967/36093920-c4dabaec-101e-11e8-8b8e-e66ec33c2725.png)
Untuk sekarang kombinasi barcode masih nomor document dari packing order, jika memang kedepannya mau diganti, itu memungkinkan.
