### ISSUE TITLE
SO - Allow double order

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#111]
Pada saat warning double order oleh customer yg sama tambahkan satu button untuk allow double order karena terdapat kasus customer memang menambah kan quantity sebelum order selesai di packing. 
![42e7a471-fa3f-4e04-8f20-f1442c09b4d8](https://user-images.githubusercontent.com/15005756/41338167-ed13a00a-6f23-11e8-8d17-2f34c66af4a2.jpeg)

**Comment by goldentrepo** [comment]
done
