### ISSUE TITLE
SO - Add Multiple cause duplicate Picking Order

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#112]
SO item yg diinput dengan add multiple menyebabkan duplikasi auto generate picking order. Berikut gambar di bawah ini adalah contohnya: 
![70b26248-b27b-4348-8430-ab83f8bb45e9](https://user-images.githubusercontent.com/15005756/41338753-a1c8f4b8-6f25-11e8-9a90-d91beaa94f30.jpeg)
![1b51cdb0-f1fd-4eb5-9021-e4d4ee4f2930](https://user-images.githubusercontent.com/15005756/41338754-a217fb58-6f25-11e8-8f23-8b9e180cdb11.jpeg)
![6443f79f-df9f-4c59-97b7-37a401bf3a2d](https://user-images.githubusercontent.com/15005756/41338755-a263f800-6f25-11e8-898b-dbed51589d1a.jpeg)

**Comment by goldentrepo** [comment]
done
