### ISSUE TITLE
Packing - Get Picking di Header

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#12]
Get Picking kolom yang perlu ditampilkan adalah nomor Tanggal Picking Order, Picking Order, Nama Customer, Nomor SO

**Comment by komsel2228** [comment]
untuk Nomor SO tidak bisa ditampilkan karena ada keterbatasan di coding programnya. jika ditampilkan, maka so yang cancel juga terlihat.  Solusi yang ditawarkan adalah SO di Form Packingnya saja.
Adapun gambaranya seperti dibawah ini:
![screen4](https://user-images.githubusercontent.com/8717967/36526601-740a209c-17e1-11e8-86f8-7134e302ac22.png)
![screen4a](https://user-images.githubusercontent.com/8717967/36526613-8a53f8f0-17e1-11e8-955a-bd14e89b29d6.png)
