### ISSUE TITLE
Stock Card - Field Arrangement

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#121]
Apakah memungkinkan jika Item ID dan Item Name ditampilkan di header, di bawah search fields? 
Jika memungkinkan maka susunan field yang ditampilkan di bawah ini tidak perlu menampilkan Item dan Item Name

Susunan field yang diinginkan mulai dari paling kiri adalah: 
Sr. No., Date, Item, Item Name, Location, Qty, Balance Qty, Valuation Rate, Voucher Type, Voucher #

**Comment by goldentrepo** [comment]
ini mksdnya gmn ya koh?  item sama item namenya dihilangkan?
Susunan field yang diinginkan mulai dari paling kiri adalah:
Sr. No., Date, **Item, Item Name**, Location, Qty, Balance Qty, Valuation Rate, Voucher Type, Voucher #

**Comment by goldentrepo** [comment]
DONE
