### ISSUE TITLE
Stock Card - Voucher Type

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#122]
Pada saat ini voucher type yang ditampilkan adalah native voucher dari ERPNext, seperti untuk perpindahan barang adalah stock entry, pengiriman barang ke customer adalah delivery note. Yang di mana pada system custom yang berjalan perpindahan barang adalah menggunakan Transfer Order dan pengiriman barang adalah menggunakan Packing List yang telah dibuat Delivery Order. 

Apakah dapat dibuat yang ditampilkan adalah voucher type sesuai dengan custom transaction yang dibuat seperti Transfer Order dan Packing list?

**Comment by goldentrepo** [comment]
DONE
