### ISSUE TITLE
Payment Entry - Customer & Supplier Payment Restriction

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#125]
User permission yang dapat membedakan payment entry hanya untuk supplier atau untuk customer saja pada user tertentu. Jika User A yang telah disetting hanya untuk pembayaran ke supplier maka User A tidak dapat melakukan Payment Entry untuk customer dan tidak bisa melihat data payment untuk customer begitu juga sebaliknya.

**Comment by goldentrepo** [comment]
DONE
