### ISSUE TITLE
Picking Order - Tampilan list

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#13]
Di list view tampilkan kolom tanggal dan customer

**Comment by komsel2228** [comment]
Sudah di tambahkan di versi 1.8.3
![picking3](https://user-images.githubusercontent.com/8717967/36089082-adec77d8-100c-11e8-8c3f-c1251bb7904e.png)
![picking2](https://user-images.githubusercontent.com/8717967/36089093-b583408a-100c-11e8-919a-481fb4c04cd1.png)
