### ISSUE TITLE
ITO - Automatic generated available?

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#15]
Apakah automatic generated ITO dari lantai 1 ke lantai 2 sudah dikerjakan?

**Comment by goldentrepo** [comment]
ini sudah dikerjakan.
beli barang, masuk ke dalam gudang di lantai1
![pr1](https://user-images.githubusercontent.com/36145352/36825607-fa68466a-1d3a-11e8-9c0e-ef93ee65a6c1.png)

lalu dibuat Sales Order
![so1](https://user-images.githubusercontent.com/36145352/36825619-074fb62e-1d3b-11e8-9a2f-b79793e192a8.png)

karena barang tidak mencukupi, di lokasi item tersebut berada, maka dibuatlah ito secara otomatis
![ito1](https://user-images.githubusercontent.com/36145352/36825483-58b46f2e-1d3a-11e8-84c4-e0f55de68a06.png)

user memasukan Qty barang yang akan dibuatkan di ITO dan lalu klik button "save" dan "submit"
setelah itu make " material transfer"
