### ISSUE TITLE
ITO - Field location from and to 

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#16]
Pada form ITO seharusnya menampilkan location from dan to

**Comment by hokgt** [comment]
from location bisa berbeda-beda, harusnya diletakkan di dalam table

**Comment by goldentrepo** [comment]
Sudah diperbaiki.
![zz1](https://user-images.githubusercontent.com/36145352/38080882-dc8bc944-336c-11e8-8137-ea6ccaeb08f2.png)
