### ISSUE TITLE
Packing - Customer should be automatic selected

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#17]
Setelah select picking order di get picking, seharusnya customer sudah otomatis selected

**Comment by komsel2228** [comment]
Sudah dimasukan, supaya Customer bisa otomatis terselect
Adapun caranya adalah sebagai berikut:
Cara pertama
- Buka Sales Order dan Make "Packing":
![salesorder1](https://user-images.githubusercontent.com/8717967/36155511-25273b6c-1107-11e8-83c0-2f23cb4cecf2.png)
![packing12345](https://user-images.githubusercontent.com/8717967/36155526-2aa7bfd0-1107-11e8-9765-b684c5f1fcb4.png)

Cara kedua
- Buka dari Packing, pilih New lalu "Get Picking Order":
![packing45](https://user-images.githubusercontent.com/8717967/36155544-36db026c-1107-11e8-9f44-c7878e5d034c.png)
![packing12345](https://user-images.githubusercontent.com/8717967/36155558-3f0146ea-1107-11e8-8a19-a71e200b5a71.png)

**Comment by goldentrepo** [comment]
Sedikit revisi, dari Sales Order sudah tidak bisa buat "Packing".
Packing harus dibuat dari Form Packing, dimana dapat menarik data Picking Order dengan menekan button "Get Picking Order"

Caranya:
- New Packing Order
- Lalu tekan button "Get Picking Order"

![packing2](https://user-images.githubusercontent.com/36145352/36486006-11189e8c-1750-11e8-9f60-0d9da43c7a34.png)

- Pilih Picking Ordernya dengan checklist, lalu tekan button "Get Items"

![packing3](https://user-images.githubusercontent.com/36145352/36486043-29776c60-1750-11e8-8018-ede78970ed72.png)

- Otomatis data dari Picking-picking order yang terpilih akan masuk ke Packing Order

![packing4](https://user-images.githubusercontent.com/36145352/36486061-307a863c-1750-11e8-8b93-fc5c74ad6e9d.png)
