### ISSUE TITLE
Packing - Duplicate Picking Order

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#18]
Picking Order di dalam Packing bisa get picking order dua kali untuk picking order yang sama

**Comment by komsel2228** [comment]
Akan dibuat tidak save jika double. Sudah benarkan di versi 1.8.3

**Comment by hokgt** [comment]
Ok, setelah diupdate saya baru close saja issue nya.

**Comment by goldentrepo** [comment]
Penjelasannya:
- New Packing Order
- Tekan button "Get Picking Order"
- Checklist Picking Order yang mau dipilih, lalu tekan button "Get Items"
![packing2](https://user-images.githubusercontent.com/36145352/36486339-e00c95fe-1750-11e8-9c27-d2c1872abfe9.png)
![packing3](https://user-images.githubusercontent.com/36145352/36486358-e93f7132-1750-11e8-993f-8adb33b60bff.png)
- Tekan button "Get Picking Order" lagi
- Checklist Picking Order yang mau dipilih, lalu tekan button "Get Items" 
  (Pilih Picking Order yang sama seperti pilihan pertama sebelumnya) --- double pilih !!
![packing3](https://user-images.githubusercontent.com/36145352/36486582-604a4e00-1751-11e8-82e6-58a6eb88a97f.png)

- Lalu isikan data-data lainnya, lalu "Save"
![packing5](https://user-images.githubusercontent.com/36145352/36486765-e65d2b8e-1751-11e8-888f-9772accea0c4.png)

- Keluar pesan error, "Picking Order" double select.
![packing6](https://user-images.githubusercontent.com/36145352/36486818-01f8a4a4-1752-11e8-90de-5e684cb990d4.png)

**Comment by hokgt** [comment]
Jika demikian tidak begitu efisien. Apakah dapat dibuat jika yang sudah diselect Picking Order makanya pada saat get picking order tidak muncul lagi.
Karena 1 Picking Order bisa banyak sekali item, jika memang terinput double maka akan susah direvisi lagi untuk Packing tersebut dan jika harus membuat Packing baru maka nomor akan tidak berurutan.
