### ISSUE TITLE
Packing - Item not showing after get picking order

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#19]
Item seharusnya secara otomatis ditampilkan setelah get picking order

**Comment by komsel2228** [comment]
prosesnya dari SO langsung generate  make "Picking Order", setelah itu item akan otomatis masuk kesana.

**Comment by hokgt** [comment]
Acuan packer saat melakukan proses packing adalah dokumen Picking Order, sehingga button di kanan atas yang Get Picking List pun harus diubah namanya menjadi Get Picking Order, kemudian packer bisa memilih Picking Order mana yang akan dipacking.

**Comment by goldentrepo** [comment]
Pada "Packing Order" terdapat button "Get Picking Order".
![packing2](https://user-images.githubusercontent.com/36145352/36487031-84b84408-1752-11e8-8430-e90c79b1d848.png)

Packer dapat memilih "Picking Order" yang akan dipacking.
![packing3](https://user-images.githubusercontent.com/36145352/36487038-89d7d9c6-1752-11e8-896b-7c9a43b95f6e.png)
