### ISSUE TITLE
Item Detail - Remove default location

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#2]
Tidak perlu input default location di dalam item detail

**Comment by komsel2228** [comment]
Kalo tidak di defaultkan, bagaimana picking bisa dibuat auto generate? mau dibaca dari mana jika tidak didefaultkan di item?
![item1](https://user-images.githubusercontent.com/8717967/36088044-123d6d14-1008-11e8-8fe0-2425e9164d84.png)

![picking1](https://user-images.githubusercontent.com/8717967/36088059-1f2c0cec-1008-11e8-8168-9efe4932db20.png)

**Comment by hokgt** [comment]
Ok, sorry saya lupa.
