### ISSUE TITLE
Packing - Auto Quantity Filling

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#21]
Pada proses packing, user packer harus memasukkan jumlah quantity barang dan inisial dus untuk setiap barang dan itu memakan waktu yang terlalu lama selain itu juga kemungkinan terjadi kesalahan quantity maximal hanya 3% dari total jenis barang yang ada di SO. 

Untuk memudahkan user, user hanya perlu merubah quantity jika memang terjadi perbedaan antara yang dipacking dengan yang ada di SO. Dari saya ada 2 metode yang bisa dilakukan yaitu : 

1. Packing Qty auto fill pada saat Packing auto generate dari SO
2. Di setiap baris setiap item di table form Packing ditambahkan kolom checkbox, setiap user mencentang check box tersebut maka quantitynya ada auto fill sesuai dengan quantity SO

**Comment by komsel2228** [comment]
Saya menggunakan cara ke-2 saja ya.
Adapun ilustrasinya seperti dibawah ini:
- New Packing Order
- Tekan Button "Get Picking Order"
![packing2](https://user-images.githubusercontent.com/8717967/36487438-74ba3b28-1753-11e8-9a5a-d380d8734791.png)

- Checklist Picking-Picking Order yang akan di Pack, lalu tekan "Get Items"
![packing3](https://user-images.githubusercontent.com/8717967/36487457-803e05ec-1753-11e8-9ea7-ddd38cd29327.png)

- Setelah itu data akan muncul.
![packing7](https://user-images.githubusercontent.com/8717967/36487677-19e133d6-1754-11e8-9379-9623bb946670.png)

- Checklist di item untuk mendapatkan qty yang dimana sama dengan SO
  (Qty Picking Order = Qty Sales Order = Qty yang di Packing)
![packing8](https://user-images.githubusercontent.com/8717967/36487726-324b893a-1754-11e8-9438-e7406fcab055.png)

**Comment by hokgt** [comment]
Ko Igna, setelah saya coba setiap record harus diklik 2 kali untuk checkbox dan klik 2 kali untuk menginput nomor box nya, artinya setiap item harus diklik 4 kali, itu cukup memakan waktu. Saya kepikir ide baru untuk meminimalkan kliknya, yaitu hilangkan checkbox nya, jika user memasukkan nomor box otomatis update Qty Paking List, artinya menggabungkan fungsi input Box dengan Checkbox. 

nb. Judul di table tolong diubah menjadi Qty Packing List dari Qty Paking List
