### ISSUE TITLE
Sales Order - Hide record level Delivery Date field

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#22]
Pada table input item di Sales Order, sembunyikan field delivery date, karena delivery date hanya akan berdasarkan satu transaksi Sales Order dan tidak ada kemungkinan berbeda delivery date dalam satu Sales Order

**Comment by komsel2228** [comment]
sudah dihiden "delivery date-nya"
![screen1](https://user-images.githubusercontent.com/8717967/36521789-5aed2da4-17cb-11e8-89e2-3086353e546f.png)
