### ISSUE TITLE
UoM - Default Changes

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#3]
Ketika membuat item, default UoM = Unit, di tab UoM select pcs tapi setelah disave dibuka kembali di dalam tab uom menjadi Unit dan langsung baris ke dua, baris pertama hilang

**Comment by komsel2228** [comment]
Penggunaan tab "UOM" itu untuk pengaturan Conversion UoM. 
Misalnya: 1 Lusin = 12 Pcs dan 1 Gross = 144 Pcs.

Adapun caranya adalah sebagai berikut:
1. Buat Item Baru / Edit Item yang sudah ada:
![item1](https://user-images.githubusercontent.com/8717967/36062182-6b4984c6-0e99-11e8-9c4e-411530e14173.png)

2. Isikan UoM dan Konversinya:
![item2](https://user-images.githubusercontent.com/8717967/36062184-708bb044-0e99-11e8-9cab-52f6540b5a80.png)

3. Setelah disave, maka otomatis UoM yang kita set sebagai satuan terkecil akan tersimpan sendiri dengan nilai konversi yaitu 1:
![item3](https://user-images.githubusercontent.com/8717967/36062187-7440a23a-0e99-11e8-9cf0-02ed78d951a0.png)

**Comment by hokgt** [comment]
Yang saya maksudkan bukan proses pembuatan UoM. Saya akan cerita step by step. 

1. Saya membuat item baru dengan default UoM = Unit
![image](https://user-images.githubusercontent.com/15005756/36070420-ce77b52a-0f2c-11e8-9ea3-414229379f31.png)

2. Pada tab UoM saya select Pcs dengan convertion factor = 1
![image](https://user-images.githubusercontent.com/15005756/36070435-1fcd5038-0f2d-11e8-9f89-08bb0133512c.png)

3. Save dan buka kembali item yang baru dibuat tersebut, scroll ke tab UoM, berubah menjadi Unit
![image](https://user-images.githubusercontent.com/15005756/36070447-4f293554-0f2d-11e8-88df-cb67db9abb9e.png)

Saya mengerti bahwa itu dikarenakan user tidak memilih default uom di header item detail, tapi jika user bisa diberitahukan bahwa default uom yang diselect dan yang terbuat di tab uom tidak sesuai, maka hal tersebut tidak menjadi masalah.

**Comment by komsel2228** [comment]
Saya tidak bisa tambahkan pengecekan di javascript karena:
1.  item,py sudah diset defaultkan oleh team ERPNext. 
![zitem1](https://user-images.githubusercontent.com/8717967/36074470-cce56b76-0f72-11e8-92e8-41520b34c3fc.png)
saya bisa ubah isi dari script ini di item.py, tetapi resikonya setiap update akan hilang karena sudah ubah di core program erpnya.

2. Action button juga hanya "save" sehingga tidak bisa ditambahkan script validate/pengecekan di item.js nya, karena item.py juga diexecute saat button "save" ditekan.

**Comment by hokgt** [comment]
Ok, mungkin bisa di pull request. :)
