### ISSUE TITLE
Receive Order - Item Selection

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#30]
Pada saat menginput item di Receive Order, kolom pertama yang dipilih adalah item barang. Di dalam list barang yang ditampilkan adalah barang-barang yang hanya ada dalam daftar barang yang sudah dibuatkan Purchase Order tapi belum diterima. Dari list browsing item tersebut juga dapat dilihat nomor PO, tgl PO, qty PO, sehingga pada saat user memilih item, informasi nomor PO, tgl PO, qty otomatis terisi pada setiap kolom di table item. 

Dengan begitu juga meminimalkan human error. Pada saat ini, user bisa memilih PO dan supplier yang berbeda dari PO yang telah disave, misalnya PO-003 atas nama supplier Tomika, item bc-336 dan pada saat input Receive Order, user bisa input PO-003 atas nama Sarang Mainan, item ms-322a.

**Comment by komsel2228** [comment]
harus atur di SOP Golden, supaya waktu buat receive order tidak bisa manual,
harus dari "Get Puchase Order".

Saya tidak bisa hilangkan manualnya karena ini berhubungan dengan banyak faktor dan framework frappe juga. 

pengaturan SOP di Golden dan atur permision dari user adalah langkah yang baik/bijak menurut saya.

**Comment by hokgt** [comment]
Dari SOP bisa diatur Ko Igna, tetapi terkadang peraturan tidak cukup mencegah human error, jika dari program menutup kemungkinan terjadinya human error maka kemungkinan terjadinya tidak ada. Ketika saya mencoba Get Purchase Order pun terjadi kemungkinan human error yaitu Get Purchase Order nomor yang sama 2 kali, dari program memang telah di prompt, tapi user mesti menghapus semua item di dalam PO yang terinput double tadi. 

Untuk manual tidak perlu dihilangkan dan memang tidak boleh dihilangkan, akan tetapi browse PO, setiap user select item, semua field di table langsung autofill dan user hanya bisa menginput satu field dan tidak bisa merubah field yang lainnya. Dengan demikian, kemungkinan terjadi error sudah tidak ada.

**Comment by goldentrepo** [comment]
sudah dibenarkan, bisa dicek,

**Comment by hokgt** [comment]
Walaupun ada prompt bahwa PO yang sama telah ditambahkan tapi duplication record tetap bertambah di dalam table. Prompt nya sudah ok tapi record juga tidak perlu ditambahkan ke dalam table.

**Comment by komsel2228** [comment]
coba dicek lagi.
