### ISSUE TITLE
Receive Order - Hide supplier

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#31]
Sembunyikan kolom supplier pada tabel item. User yang menginput Receive Order tidak perlu mengetahui supplier nya. Sehingga semua informasi supplier pada Receive Order harus disembunyikan.

**Comment by komsel2228** [comment]
saya akan hide supplier. 
Kenapa ada muncul dan tidak dihide? karena ini buat kami check ulang waktu pengkodingan.

**Comment by goldentrepo** [comment]
sudah dihiden
![ro1](https://user-images.githubusercontent.com/36145352/36833475-0dac7b0c-1d62-11e8-9aca-79164493c4e2.png)
