### ISSUE TITLE
Receive Order - Conversion Factor

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#32]
Pada golden versi 1.10.8, setelah dicoba memasukkan item dan save, conversion factor uom tidak otomatis terisi, yang di mana seharusnya mengacu pada conversion factor yang telah ditetapkan pada saat pembuatan uom.

**Comment by goldentrepo** [comment]
conversion factor dari item mengikuti saat pengisian item di Purchase Order.
ini sudah dibenerin di receive order sehinga mengikuti data yang ada di Purchase Order.

**Comment by hokgt** [comment]
Masalah berikutnya adalah jika Receieve Order digenerate dengan menggunakan UoM yang berbeda dari PO tidak bisa disave

**Comment by komsel2228** [comment]
casenya seperti ini:
1 lusin = 12 unit.

a. Jika buat Purchase Order, itemnya diisi dengan unit maka di receiver order dapat seperti ini:
    - Terima dengan satuan itemnya unit
    - Terima dengan satuannya lusin
b. Jika buat Purchase Order dengan itemnya diisi lusin, maka receive order hanya bisa diterima 
    dengan satuan Lusin

**Comment by komsel2228** [comment]
Case yang A
![zx21](https://user-images.githubusercontent.com/8717967/38080312-4c251956-336b-11e8-86ed-ebc0bc2b928c.png)
![zx3](https://user-images.githubusercontent.com/8717967/38080321-515e36aa-336b-11e8-957b-9ce5ab9fde9a.png)
![zx22](https://user-images.githubusercontent.com/8717967/38080411-965484c6-336b-11e8-8ab4-f2e1c9e90ace.png)






Case yang B
![zx11](https://user-images.githubusercontent.com/8717967/38080020-8a89f9ba-336a-11e8-8e79-bb21ca6cbca3.png)
![zx1](https://user-images.githubusercontent.com/8717967/38080018-8a5174c8-336a-11e8-9ce8-ae5956b572f9.png)
![zx2](https://user-images.githubusercontent.com/8717967/38080127-dce6300c-336a-11e8-962c-c2d3f8430e39.png)

**Comment by hokgt** [comment]
Apakah maksudnya program sudah diupdate dapat mengakomodir kedua case tersebut?

**Comment by komsel2228** [comment]
Jika PO dengan Unit, RO bisa cover Unit atau Lusin
Tetapi jika PO dengan Lusin, maka RO hanya bisa dengan Lusin, tidak bisa dengan Unit.

**Comment by hokgt** [comment]
Ok, noted
