### ISSUE TITLE
ITO tidak bisa pilih item code (kursornya freeze / tanda bulat)

### ISSUE THREAD

**Issue by benarivo** [goldentrepo/golden#34]
untuk yang golden dan yang localhost tidak bisa pilih item code di tabel, kursornya tidak bisa discreenshot

![screenshot from 2018-03-09 10-14-22](https://user-images.githubusercontent.com/36909925/37188628-bbe20f0e-2382-11e8-8df4-a4951c76fd2b.png)

**Comment by goldentrepo** [comment]
modul ito sudah di hapus. diganti dengan modul "Tranfer Order"

harusnya sudah fix untuk case ini
