### ISSUE TITLE
Designation Department

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#52]
Picker, Packer, Receiver & Checker digabung menjadi 1 departemen yaitu Warehouse
Driver & Driver Helper digabung menjadi departemen logistic

User bisa melakukan customizing asosiasi departemen ke posisi di dalam transaksi

**Comment by goldentrepo** [comment]
Done

**Comment by hokgt** [comment]
Terdapat field department yang perlu diisi oleh user. Bukankah seharusnya sudah otomatis diisi oleh sistem berdasarkan department yang telah ditentukan pada saat pembuatan employee?
