### ISSUE TITLE
Deliver Order - Get Packing List Error

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#57]
Packing List yang sudah dibuat dan submitted tidak tampil pada saat Get Packing List di Delivery Order

**Comment by goldentrepo** [comment]
apakah sudah dibuat invoice? karena akan muncul di delivery order ketika packing list nya sudah dibuat invoice.

**Comment by hokgt** [comment]
Ok, setelah dibuat Sales Invoice sudah muncul
