### ISSUE TITLE
Purchase Order - UoM default price

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#6]
Ubah default price menjadi price dengan UoM dasar bukan berdasarkan price dengan satuan transaksi

**Comment by komsel2228** [comment]
ini maksudnya apa ya? bisa tolong dibantu jelaskan lebih detail.

**Comment by hokgt** [comment]
Pada saat ini, di setiap transaksi yang berhubungan dengan harga, harga yang tampil akan mengacu kepada uom selected. Sebagai contoh jika Item A terdapat 2 uom, Pcs dan Lusin, harga 1 pcs barang Item A adalah Rp. 1.000 dan setiap kita membuka transaksi dengan uom lusin, harga yang tampil adalah Rp. 12.000 karena Rp. 1.000 x 12 pcs = harga 1 lusin. 

Yang diinginkan adalah:
Pada setiap transaksi yang berhubungan dengan harga dapat disetting dengan 2 opsi:
1. Kondisi sama seperti skenario di atas (default dari erpnext)
2. User dapat memilih maintain price based on base uom. Artinya setiap menginput transaksi yang berhubungan dengan harga, harga yang tampil bukan sesuai dengan uom yang diinput tapi sesuai dengan base uom. Sebagai contoh dengan skenario di atas: Item A jual 2 lsn tapi harga yang tampil adalah Rp. 1.000 bukan Rp. 12.000 akan tetapi subtotal dari masing-masing item tetap sama seperti opsi 1 Rp. 24.000

**Comment by komsel2228** [comment]
di ERPNext prosedurnya seperti ini:
![so_price](https://user-images.githubusercontent.com/8717967/36782223-d6bfd8da-1caa-11e8-971c-6e6d4bdeaca9.png)

untuk opsi ke-2 mau diubah seperti dibawah ini:
![so_price 2](https://user-images.githubusercontent.com/8717967/36782398-702f631e-1cab-11e8-8a53-7434cc740221.png)
yang dimana hasil nya adalah seperti dibawah ini:
![so_price1](https://user-images.githubusercontent.com/8717967/36782675-3eabc980-1cac-11e8-9539-8e53e1893779.png)
pertanyaannya, apakah tidak menjadi rancu ya?

**Comment by hokgt** [comment]
Benar seperti yang disimulasikan Ko Igna dan tidak rancu karena memudahkan customer untuk mengetahui harga dasarnya. 

Di header tolong ditambahkan checkbox untuk memilih display rate nya. Jika user mencentang Display UoM base rate maka judul di table Rate Base UoM dan harga akan selalu mengacu ke base uom rate.
