### ISSUE TITLE
SO - Net Amount Field Blank

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#66]
Net Amount pada SO tidak ada value setelah add item 
<img width="1277" alt="screen shot 2018-05-24 at 10 36 04" src="https://user-images.githubusercontent.com/15005756/40463253-6b444d58-5f3e-11e8-80a4-68e026f1b099.png">

**Comment by goldentrepo** [comment]
done

**Comment by hokgt** [comment]
Net Amount malah tidak muncul di versi 19.4
<img width="1281" alt="screen shot 2018-05-24 at 19 25 13" src="https://user-images.githubusercontent.com/15005756/40485272-4495a1a8-5f88-11e8-84cb-6a74dbc959dd.png">
