### ISSUE TITLE
SO - Auto fill error

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#67]
Warehouse routing field diklik tapi tidak diisi dan belum dipilih kemudian klik ke field lain, field warehouse otomatis terisi walaupun warehouse routing belum dipilih
![may-24-2018 10-50-06](https://user-images.githubusercontent.com/15005756/40463588-4a388ef6-5f40-11e8-84f7-6638417d2c64.gif)

**Comment by goldentrepo** [comment]
done
