### ISSUE TITLE
Packing - Multiple customer should be prohibited

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#69]
Pada Packing user dapat menginput Picking Order lebih dari satu customer yang seharusnya tidak boleh, karena 1 picking order hanya berlalu untuk 1 customer. 

Ide dari saya ialah Picking Order yang sudah dimasukkan maka filter customer otomatis mengikuti customer yang telah dimasukkan dan dibuat read only. Kecuali user menghapus semua item dan picking order yang terisi, filter akan kembali seperti awal.

**Comment by goldentrepo** [comment]
update ke versi 1.19.3
done

**Comment by hokgt** [comment]
Setelah dicoba masih sama seperti sebelumnya
