### ISSUE TITLE
Main Menu - Item Price Link

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#70]
Menu Item Price pada main menu link nya bukan ke Item Price List tapi ke Item Price Report

<img width="465" alt="screen shot 2018-05-24 at 12 30 23" src="https://user-images.githubusercontent.com/15005756/40466144-62abdd5e-5f4e-11e8-9453-14fa23b661df.png">

Keluarnya Item price Report: 
<img width="1258" alt="screen shot 2018-05-24 at 12 31 41" src="https://user-images.githubusercontent.com/15005756/40466160-7919694e-5f4e-11e8-9a9c-21e0e67a0961.png">

Seharusnya : 
<img width="1263" alt="screen shot 2018-05-24 at 12 32 21" src="https://user-images.githubusercontent.com/15005756/40466174-894ad50a-5f4e-11e8-8b34-4a27121a425b.png">

**Comment by goldentrepo** [comment]
itu defaultnya dari erpnext seperti itu koh.
