### ISSUE TITLE
Product Receipt per container

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#8]
Product receipt diinput berdasarkan per container bukan per supplier

**Comment by komsel2228** [comment]
Alur pembelian barang adalah sebagai berikut:
1. PO (Purchase Order) 
    a. Saat PO sudah dibuat dan disave, maka statusnya "Draft"
    b. Jika sudah oke, bisa di Submit 
    c. Tidak ada Jurnal.
2. Receive Order (saat barang sudah datang dan diterima).
    a. Receive Order ini per Container
    b. Bisa lebih dari 1 PO dalam 1 Receive Order
    c. Bisa lebih dari 1 Supplier dalam 1 Receive Order
    d. Tidak ada Jurnal.
3. Saat Receive Order di Submit, maka Purchase Receipt otomatis terbuat dan terjurnal.
    a. 1 Receive Order bisa banyak Purchase Receipt (karena purchase receipt base on supplier).
    b. Ada Proses penjurnalan "Persediaan"
4. Purchase Invoice

**Comment by komsel2228** [comment]
Ini tampilan Receiver Order per Container
![receive order](https://user-images.githubusercontent.com/8717967/36468456-009eae46-1716-11e8-9c29-579b2d97f746.png)
