### ISSUE TITLE
Receive Order - Packaging Field

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#91]
Pada Receive Order masih belum ditambahkan field jumlah packaging yang fungsinya untuk mencocokkan total jumlah packaging yang diterima dengan total packaging yang diinput pada receive order item.

Berikut adalah yang perlu ditambahkan:

1. Pada header tambahkan field total packaging yang diinput oleh user, user akan input berdasarkan total packaging dari surat jalan expedisi
2. Pada receive order item, setiap record ditambahkan field packaging, user akan menginput jumlah packaging per item berdasarkan jumlah packaging dari perhitungan penerima barang
3. Pada saat user submit document, system akan membandingkan total packaging pada receive order item berbanding dengan total packaging yang diinput di header, jika berbeda maka document tidak dapat disubmit dan meminta user untuk melakukan pengecekan ulang

**Comment by goldentrepo** [comment]
done
