### ISSUE TITLE
Sales Order - Missing Item Code

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#93]
Pada saat user menginput Sales Order Item dengan Add Multiple, item code tidak terinput walaupun pada list view sales order item sudah terisi, berikut adalah penjelasannya. 

Item baris 1 dan 2 diinput menggunakan add row satu per satu, sedangkan item 3 menggunakan add multiple:
<img width="1218" alt="screen shot 2018-06-04 at 13 43 40" src="https://user-images.githubusercontent.com/15005756/40902292-ba2cd47c-67fd-11e8-8cc8-af6f264a2d9e.png">

Pada saat submit muncul error berikut:
<img width="1218" alt="screen shot 2018-06-04 at 13 43 53" src="https://user-images.githubusercontent.com/15005756/40902337-e6a489f0-67fd-11e8-8085-1a7d30c76f0e.png">

Setelah dilakukan pengecekkan di item yang memakai add multiple: 
<img width="976" alt="screen shot 2018-06-04 at 13 44 19" src="https://user-images.githubusercontent.com/15005756/40902359-f7f91d6a-67fd-11e8-975a-c907a9aec91c.png">

**Comment by goldentrepo** [comment]
done
