### ISSUE TITLE
Sales Order - Multiple Order Warning

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#94]
Pada system yang lama, jika user sudah membuat SO 1 untuk customer Budi dengan item A, maka jika user membuat lagi SO 2 (SO 1 belum selesai diproses) dengan customer Budi dan dengan item A, system akan memberikan warning, bahwa customer Budi telah order item A terdapat pada SO 1 yg belum selesai diproses sebanyak qty SO 1. Dengan demikian mencegah terjadinya item yg terinput double pada customer yg sama.

**Comment by goldentrepo** [comment]
ini keluar warningnya pada saat save atau submit koh?

**Comment by hokgt** [comment]
Keluarnya pada saat user save

**Comment by goldentrepo** [comment]
done

**Comment by hokgt** [comment]
Setelah ditest tidak berfungsi. Saya create SO-0073 dan submit kemudian create lagi SO-0075 dengan customer yang sama dan item yang sama tapi bisa disave.
