### ISSUE TITLE
Purchase Invoice - Inventory & Non Inventory Item

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#97]
Pada system sebelumnya, item yang dapat diselect pada purchase invoice hanyalah item yang telah diinput di dalam receive order. Kondisi ini untuk meminimalkan human error pada saat menginput purchase invoice, sehingga dipastikan hanya barang yang telah diterima yang dapat dibuat Purchase Invoicenya. 

Akan tetapi pada system yang baru juga harus mengakomodir pembelian barang non inventory seperti atk, barang titipan customer, dsb. Sehingga pembatasan hanya item yang dibuatkan receive order yang dapat dibuatkan purchase invoice membuat purchase invoice tidak dapat mengakomodir kondisi tersebut. 

Oleh karena itu, system baru ini dirancang dengan kondisi sebagai berikut: 
1. Pada item group ditambahkan check box apakah non inventory item. Jika user mencentang checkbox tersebut artinya semua item yang dalam item group tersebut adalah termasuk dalam non inventory item
2. Pada Purchase Invoice, header memberikan check box pilihan non inventory item (secara default tidak tercentang karena mayoritas PI adalah inventory item)
3. Pada Purchase Invoice, setelah user memilih supplier, maka tombol get items from receive order dapat diklik dan user dapat memilih get items dari receive order yang mana
4. Setelah terpilih, system otomatis mengisi purchase invoice item dengan item yang terdapat pada Purchase Order dengan supplier terpilih yang telah diinput Receive Ordernya
5. Jika user tidak mencentang non inventory checkbox akan tetapi mengisi purchase invoice item dengan item non inventory, maka user tidak dapat save purchase invoice tersebut dan memberikan prompt bahwa item yang diinput adalah item dalam non inventory group yang dikenali dari item group (point 1)
6. Jika user mencentang non inventory checkbox maka, get items from receive order tidak dapat diklik atau dihilangkan dan jika user mengisi dengan item dalam inventory group maka purchase invoice tidak bisa disave dan system akan memberikan prompt bahwa item mana yang terinput adalah item inventory group

**Comment by goldentrepo** [comment]
done

**Comment by hokgt** [comment]
Dan untuk revisi daripada mengambil po supplier, lebih baik yang dipilih adalah receive order, sehingga hanya menampilkan saja barang yang diterima dari supplier yang diinput.

**Comment by hokgt** [comment]
Justru karena alasan barang harus yang diterima terlebih dahulu maka lebih baik select RO. Walaupun user yang menginput RO tidak mengetahui PO mana tapi setiap barang yang diterima harus dibuatkan po terlebih dahulu sehingga setiap barang yang diterima adalah barang yang terdapat di PO dan dibuatkan RO. 

Mengapa walaupun PO yang belum 100% receipt sudah harus dibuatkan PI nya, karena satu PO dari kita bisa dibagi menjadi beberapa PI oleh supplier, artinya jika PO yang kita terbitkan untuk supplier Andi terdapat 10 item dan Supplier Andi bisa mengirimkan bertahap PO tersebut, dari 10 item, dikirim dulu 6 item dalam 1 PI dan 3 item berikut dengan quantity 50% dari PO dalam 1 PI dan sisanya dalam 1 PI lagi. Dengan demikian tidak bisa menunggu PO 100% receipt baru buka PI tetapi berdasarkan barang yang telah direceipt dari PO supplier mana yang bisa kita bukakan PI.

**Comment by goldentrepo** [comment]
done
